- name: "Create Runner service user {{ runner_user }}"
  become: true
  ansible.builtin.user:
    name: "{{ runner_user }}"
    create_home: true
    home: /opt/gh-runner
    shell: /bin/bash
    state: present

- name: "Allow passwordless sudo to {{ runner_user }}"
  become: true
  community.general.sudoers:
    name: "managed-by-ansible-github-runner"
    nopassword: true
    commands: "ALL"
    state: "present"
    user: "{{ ansible_user }}"
    runas: "{{ runner_user }}"
