---
provisioner:
  name: ansible
  config_options:
    defaults:
      verbosity: 0
  playbooks:
      converge: converge.yml
      cleanup: cleanup.yml
      verify: verify.yml
dependency:
  name: galaxy
lint: |
  yamllint .
  ansible-lint .
driver:
  name: docker
platforms:
  - name: "${os:-ubuntu20}-${tag:-latest}"
    image: "${namespace:-monolithprojects}/systemd-${os:-ubuntu20}:${tag:-latest}"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:${MOLECULE_DOCKER_VOLUMES:-ro}" # Use "ro" for cgroup v1 and "rw" for cgroup v2
    cgroupns_mode: ${MOLECULE_DOCKER_CGROUPS_MODE:-"private"} # Use "private" for cgroup v1 and "host" for cgroup v2
    privileged: true
    pre_build_image: true
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - dependency
    - lint
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
